"""add_dimensions_and_reference_product

Revision ID: f2de4c704bec
Revises: ef994d4ccda2
Create Date: 2026-04-02 01:52:31.881622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2de4c704bec'
down_revision: Union[str, None] = 'ef994d4ccda2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'dimensions')
    # ### end Alembic commands ###
